#!/usr/bin/perl -w

my @table_fields = ();
my @table_type_length = ();
my @table_type = ();

open(SQL_FP, "<create_table.txt") or die "creat_table.txt can not open";

while(<SQL_FP>){
    if($_ =~ /`(.*)`/ and $_ !~ /KEY./)
    {
        push(@table_fields, $_ =~ /`(.*)`/);
    }
    if($_ =~ /\((.*)\)/ and $_ !~ /KEY./)
    {
        push(@table_type_length, $_ =~ /\((.*)\)/);
    }
    if($_ =~ /`\s(.*)\(/ and $_ !~ /KEY./)
    {
        push(@table_type, $_ =~ /`\s(.*)\(/);
    }
}
close(SQL_FP);

#print "@table_fields\n";
#print "@table_type_length\n";
#print "@table_type\n";

my $data = join('', <DATA>);
my ($db_src, $db_h, $dbaccess_c, $dbaccess_h, $dbaccessEnc_c, $dbaccessEnc_h) = ($data =~ m|^(.+)-=#=-\n(.+)-=#=-\n(.+)-=#=-\n(.+)-=#=-\n(.+)-=#=-\n(.+)|s);


my $field_enum;
my $table_name_first_up;
my $table_name_all_up;
my $field_str_for;
my $field_column;

$table_name_first_up = ucfirst($table_fields[0]);
$table_name_all_up = uc($table_fields[0]);

foreach $field_str_for (@table_fields[1 .. $#table_fields])
{
    $field_enum .= "\U    DB_CM_$table_fields[0]_$field_str_for,\n";
}

$field_column = "    {DB_CM_\U$table_fields[0]_$table_fields[1]\E, \"$table_fields[1]\", AUTO_DEFAULT_COLUMN},\n";
foreach $field_str_for (@table_fields[2 .. $#table_fields])
{
    $field_column .= "    {DB_CM_\U$table_fields[0]_$field_str_for\E,\"$field_str_for\", 0},\n";
}

my $field_get;
my $struct_define;
#foreach $i (@table_fields;@table_type)
for ($i = 0; $i <= $#table_type; $i += 1)
{
    if($table_type[$i] eq "tinyint")
    {
        $field_get .= "        user->$table_fields[$i] = EmicAtoi(Row[DB_CM_\U$table_fields[0]_$table_fields[$i]])\n";
        $struct_define .= "    int                $table_fields[$i];\n"; 
    }
    elsif($table_type[$i] eq "bigint")
    {	   
	$field_get .= "        user->$table_fields[$i] = EmicAtol(Row[DB_CM_\U$table_fields[0]_$table_fields[$i]])\n";
	$struct_define .= "    unsigned long      $table_fields[$i];\n";
    }
    elsif($table_type[$i] eq "varchar")
    {	  
	$field_get .= "        Emic_strncpy(user->$table_fields[$i], Row[DB_CM_\U$table_fields[0]_$table_fields[$i]]\E, sizeof(user->$table_fields[$i])])\n";
        $struct_define .= "    char               $table_fields[$i]\[$table_type_length[$i]\];\n";
    }
}

#print "$field_get\n";
#print "$struct_define\n";

$db_src =~ s|%TABLE_NAME_FIRST_UP%|$table_name_first_up|sg;
$db_src =~ s|%FIELD_ENUM%|$field_enum|sg;
$db_src =~ s|%FIELD_COLUMN%|$field_column|sg;
$db_src =~ s|%TABLE_NAME_ALL_UP%|$table_name_all_up|sg;
$db_src =~ s|%FIELD_GET%|$field_get|sg;
print "$db_src\n";

$db_h =~ s|%TABLE_NAME_UP%|\U$table_fields[0]|sg;
$db_h =~ s|%TABLE_NAME%|$table_fields[0]|sg;
$db_h =~ s|%TABLE_NAME_ALL_UP%|$table_name_all_up|sg;
$db_h =~ s|%TABLE_NAME_FIRST_UP%|$table_name_first_up|sg;
$db_h =~ s|%STRUCT_DEFINE%|$struct_define|sg;
print "$db_h\n";

$dbaccess_c =~ s|%TABLE_NAME_FIRST_UP%|$table_name_first_up|sg;
print "$dbaccess_c\n";

$dbaccess_h =~ s|%TABLE_NAME_ALL_UP%|$table_name_all_up|sg;
$dbaccess_h =~ s|%TABLE_NAME_FIRST_UP%|$table_name_first_up|sg;
print "$dbaccess_h\n";

$dbaccessEnc_c =~ s|%TABLE_NAME_FIRST_UP%|$table_name_first_up|sg;
print "$dbaccessEnc_c\n";

$dbaccessEnc_h =~ s|%TABLE_NAME_FIRST_UP%|$table_name_first_up|sg;
print "$dbaccessEnc_h\n";


##EOF##
__DATA__
#include "DatabaseCm%TABLE_NAME_FIRST_UP%.h"

enum
{
%FIELD_ENUM%
};

static DATABASE_CLOUMN_NAME Cm%TABLE_NAME_FIRST_UP%Columns[] =
{
%FIELD_COLUMN%
};

int DbGetCm%TABLE_NAME_FIRST_UP%ByCondition(MYSQL *pDb, char *dbName, char *condition, EMICALL_DB_CM_%TABLE_NAME_ALL_UP% *list)
{
    char                sql_str[MAX_SQL_LEN+1] = {0};
    struct select_sql   select_entry           = {0};
    int                 ret                    = 0;
    int                 row_num                = 0;
    MYSQL_RES           *res;
    MYSQL_ROW           Row;
    EMICALL_DB_CM_%TABLE_NAME_ALL_UP%  *user = list;    
    
    printf(select_entry.tables, "%s.%s", dbName, DATABASE_CM_%TABLE_NAME_ALL_UP%_TABLE_NAME);
    DbSqlColumnAssembling(select_entry.columns, CmGroupColumns, DB_CM_%TABLE_NAME_ALL_UP%_COLUMN_NUM, TRUE);
    Emic_strncpy(select_entry.conditions, condition, sizeof(select_entry.conditions)); 
    
    construct_select_sql(sql_str, &select_entry);
    EmicDatabaseExecute(pDb, sql_str, ret);
    if(ret)
        return ret;
    ret = DbMysqlGetTable(pDb, &res);
    if(ret)
        return ret;
 
    row_num = mysql_num_rows(res);
    if(row_num > 0)
    {
        Row = mysql_fetch_row(res);
	if(!Row)
        {
	    DbMysqlFreeResult(res);
	    return ret;
	}

%FIELD_GET%	
    }

    DbMysqlFreeResult(res);
    
    return ret;
}

static char *DbCm%TABLE_NAME_FIRST_UP%ColumnName(int seq)
{
    if (seq >= 0 && seq < sizeof(Cm%TABLE_NAME_FIRST_UP%Columns)/sizeof(DATABASE_CLOUMN_NAME))
        return Cm%TABLE_NAME_FIRST_UP%Columns[seq].name;
    return NULL;
};


-=#=-
#ifndef __DATA_BASE_CM_%TABLE_NAME_UP%_H__
##define __DATA_BASE_CM_%TABLE_NAME_UP%_H__
##include "CmEmic_DbApi.h"
##include "CmEmicBaseDefinition.h"

#define DATABASE_CM_%TABLE_NAME_ALL_UP%_TABLE_NAME     "%TABLE_NAME%"

typedef enum __cm_%TABLE_NAME%_action
{

}CM_%TABLE_NAME_ALL_UP%_ACTION;

typedef struct __emicallcm_db_cm_group__
{
%STRUCT_DEFINE%
}EMICALL_DB_CM_%TABLE_NAME_ALL_UP%;

int DbGetCm%TABLE_NAME_FIRST_UP%ByCondition(MYSQL *pDb, char *dbName, char *condition, EMICALL_DB_CM_%TABLE_NAME_ALL_UP% *list);

#endif

-=#=-
/*
 *  Server source file for DbAccess function Cm%TABLE_NAME_FIRST_UP%: DbAccessCm%TABLE_NAME_FIRST_UP%.c
 */
#include "CmDbAccessThread.h"
#include "CmDbAccessEncapsulation.h"

int DbServerChannelCmGroup(MYSQL *pDb, char *src_data, char **ret_data, int *ret_len)
{
    int                        ret      = 0;
    int                        dataLen  = 0;
    unsigned int               count    = 0;
    Cm%TABLE_NAME_FIRST_UP%_REQUEST_PARAM      *request = (Cm%TABLE_NAME_FIRST_UP%_REQUEST_PARAM *)src_data;
    Cm%TABLE_NAME_FIRST_UP%_RESPONSE_DATA      *rspData = NULL;
    
    if(NULL == pDb || NULL == request || NULL == ret_data || NULL == ret_len)
    {
        emi_sys_log(LOG_LEVEL_ERROR, CM_DB_ACCESS_THREAD_NAME, "Invalid parameter");
        return DB_ERROR_CODE_INVALID_ARGUMENT;
    }

    rspData = (Cm%TABLE_NAME_FIRST_UP%_RESPONSE_DATA *)EmicMalloc(sizeof(Cm%TABLE_NAME_FIRST_UP%_RESPONSE_DATA)); 
    if(rspData == NULL)
    {
        emi_sys_log(LOG_LEVEL_ERROR, CM_DB_ACCESS_THREAD_NAME, "EmicMalloc failed");
	ret = DB_ERROR_CODE_MEMORY_ALLOC_FAILED;
        return ret;
    }

    memset(rspData, 0, sizeof(Cm%TABLE_NAME_FIRST_UP%_RESPONSE_DATA));	    
    rspData->actionType = request->actionType;

    /* Add code for database access. */
    if (request->actionType == CM_GET_GROUP_INFO_BY_SEID_AND_CCGEID)
    {
        ret = ;
	if(ret)
	{
            emi_sys_log(LOG_LEVEL_ERROR, CM_DB_ACCESS_THREAD_NAME, "failed,ret %d", ret);
	    FREE_IF_NOT_NULL(rspData);
	    return ret;
	}   
    }
    else
    {
        ret = DB_RET_NO_ERROR;
    }

    /* Add code for database access, end */

    /* set ret_data and ret_len value, if no response, they call be all NULL */
    *ret_data = (char *)rspData;
    *ret_len = dataLen;

    return ret;

};

-=#=-
/*
 *  Server header file for DbAccess function Cm%TABLE_NAME_FIRST_UP%: DbAccessCm%TABLE_NAME_FIRST_UP%.h
 */
#ifndef __DB_ACCESS_Cm%TABLE_NAME_FIRST_UP%_H__
#define __DB_ACCESS_Cm%TABLE_NAME_FIRST_UP%_H__

#include "db_api.h"
 
#int DbServerChannelCm%TABLE_NAME_FIRST_UP%(MYSQL *pDb, char *src_data, char **ret_data, int *ret_len);

#endif

-=#=-
/*
 *  Source file for DbAccess function Cm%TABLE_NAME_FIRST_UP%: DbAccessCm%TABLE_NAME_FIRST_UP%Encapsulation.c
 */
#include <string.h>
#include <errno.h>
#include "json-c/json.h"
#include "json-c/json_object_private.h"
#include "EmicBaseCommChannel.h"
#include "CmDbAccessEncapsulation.h"
#include "CmDbAccessJsonParse.h"

-=#=-
/*
 *  Header file for DbAccess function Cm%TABLE_NAME_FIRST_UP%: DbAccessCm%TABLE_NAME_FIRST_UP%Encapsulation.h
 *  Should be included by DbAccessEncapsulation.h and DbAccessJsonParse.h.
 */
#ifndef __DB_ACCESS_Cm%TABLE_NAME_FIRST_UP%_ENCAPSULATION_H__
#define __DB_ACCESS_Cm%TABLE_NAME_FIRST_UP%_ENCAPSULATION_H__
   
#include "CmEmicBaseDefinition.h"
#include "DatabaseCm%TABLE_NAME_FIRST_UP%.h"
 
