#!/usr/bin/perl -w

my @table_fields = ();

open(SQL_FP, "<create_table.txt") or die "creat_table.txt can not open";

while(<SQL_FP>){
    if($_ =~ /.*`(.*)`/ and $_ !~ /KEY.*/)
    {
        push(@table_fields, $_ =~ /.*`(.*)`/);
    }

}
close(SQL_FP);

print "@table_fields\n";

my $data = join('', <DATA>);
$data =~ s|%TABLE_NAME%|$table_fields[0]|sg;
$data =~ s|%FIELD_NAME%|$table_fields[1]|sg;

$enum_str = "\U    $table_fields[2],\n    $table_fields[3],\n";
$data =~ s|%FIELD_ENUM%|$enum_str|sg;

print "$data\n";

##EOF##
__DATA__

enum
{
    DB_CM_%TABLE_NAME%_%FIELD_NAME%,
};

enum
{
%FIELD_ENUM%
};
